POST http://localhost:6000/api/auth/signup
Content-Type: application/json

{
  "FirstName": "Dattu",
  "LastName": "joje",
  "email": "dattu@exaeekpjle.com",
  "phone": 9823495009,
  "password": "mypassword123"
}
