POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "dattu@exampl.com",
  "password": "mypassword123"
}


### 
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "FirstName": "Dattu",
  "LastName": "Joje",
  "email": "dattu@exampl.com",
  "phone": "9823495001",
  "password": "mypassword123"
}



### 
POST http://localhost:11434/api/generate

{
  "model": "llama3.1:8b",
  "prompt": "Hello, explain AI roadmap for a student.",
  "max_tokens": 512,
  "stream": false
}


####
POST http://localhost:5000/api/ai/ask
Content-Type: application/json

{
  ""
  "prompt": "give road map of data science"
}


####
POST  http://localhost:5000/api/user/userinfo



#### 
GET http://localhost:8000/api/chats
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjJiNjBjNGMyMDQ5OWNlNjYyZDlmZiIsImlhdCI6MTc4MDY2MjgyOCwiZXhwIjoxNzgwNjY2NDI4fQ.wuo-x7wsyuLi_U8YqFd7rxAWrZ3-Qum8aG6hkFSyc64