POST http://localhost:8000/api/auth/signup
Content-Type: application/json

{
  "FirstName": "Dattu",
  "LastName": "joje",
  "email": "dattu@exaemple.com",
  "phone": 9823495758,
  "password": "mypassword123"
}


### login test

POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "identifier": "dattu@example.com",
  "password": "mypassword123"
}
